### ISSUE TITLE
New name for Repo

### ISSUE THREAD

**Issue by schorrm** [schorrm/pybaseball#6]
As we're maintaining this here now, we probably need a new name (for PyPI among others, and differentiation etc.)
Taking suggestions

**Comment by TylerLiu42** [comment]
SabermetricScholar, SabermetricSage? (too many syllables perhaps)

**Comment by schorrm** [comment]
God no

**Comment by schorrm** [comment]
Maybe `pybaseball2` if nothing inspires. If we're going the sabermetrics route, just `saberpy` or something

**Comment by TylerLiu42** [comment]
I like saberpy

**Comment by schorrm** [comment]
PySaber is taken, pysabermetrics seems available, saberpy is okay but not ideal, open to other options

**Comment by TylerLiu42** [comment]
Does the name have to include "py"?
